### ISSUE TITLE
Other packages cannot be found from within package

### ISSUE THREAD

**Issue by Timple** [colcon/colcon-top-level-workspace#4]
This works:

```bash
cd /ws
colcon build --packages-select robotA
```
`Using workspace root /ws`
`Starting >>> robotA`

This does not work:
```
cd /ws/src/robotB/include
colcon build --packages-select robotA
```
`Using workspace root /ws`
`[1.336s] WARNING:colcon.colcon_core.package_selection:ignoring unknown package 'robotA' in --packages-select`

I suspect the find is done before the directory switching or something.

**Comment by cottsay** [comment]
Have you built at least one package in the workspace to create the `build` directory prior to trying to build from the subdirectory?

**Comment by Timple** [comment]
Ye, the complete workspace is build actually.

**Comment by cottsay** [comment]
You're using the implementation proposal from here: https://github.com/rhaschke/colcon-top-level-workspace/

You should file your issue there.

**Comment by Timple** [comment]
Apologies, wasn't aware but you are right!

**Comment by rhaschke** [comment]
@Timple, as you didn't open a new issue: The answer to your question is in the docs ([README.md](https://github.com/rhaschke/colcon-top-level-workspace/blob/main/README.md?plain=1#L12-L13)):
> Package discovery is done relative to the current working directory. Thus, to build all packages in the current folder, just run `colcon build`.
> To build all packages in the workspace, specify the special token `ROOT` for the `--base-paths` argument: `colcon build --base-paths ROOT`.
